-- Generated by installed auth@1.7.7; rateLimit storage only. Prior migrations are immutable.
create table "rateLimit" ("id" text not null primary key, "key" text not null unique, "count" integer not null, "lastRequest" bigint not null);
